# Generated by Django 4.1.7 on 2023-03-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_scrapedrecipeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedRecipeItem',
        ),
    ]
