# Generated by Django 4.1.7 on 2023-03-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_file_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extension',
            new_name='file_type',
        ),
    ]
